spring:
#  多环境切换
  profiles:
    active: dev
#    国际化配置
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  datasource:
    username: ENC(OQtoPo5z6j62Derk8a5+Xw==)
    password: ENC(vhZHBzMnEKVLSNJRf6eb5w==)
    url: jdbc:mysql://localhost:3306/sbp_transaction?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    schema:
      - classpath:sql/department.sql
      - classpath:sql/employee.sql
    initialization-mode: always

  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true

  # mvc日期格式化配置
  mvc:
    date-format: yyyy-MM-dd
#    restful 风格配置使用，post,get,put,delete
    hiddenmethod:
      filter:
        enabled: true

  #  配置redis
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.88.135:26379,192.168.88.133:26380,192.168.88.136:26381
    database: 1
    ssl: false
    jedis:
      pool:
        max-active: 1000
        max-idle: 50
        min-idle: 20
        max-wait: 300ms
    timeout: 3000ms


server:
  servlet:
    context-path: /sbo
    session:
      timeout: 30000ms

person:
  lastName: jack${random.uuid}
  age: ${random.int}
  boss: true
  birth: 2020/2/18
  maps: {addr: shiyan,ip: 2013}
  lists:
    - lisi
    - jackson
  dog:
    name: ${person.lastName}_haha
    age: 5

#开启springboot的debug，打印自动配置报告，哪些配置生效
#debug: true

# 没有指定日志路径，默认项目下边
logging:
  file:
    path: e:/java_project/sbo/log
  # 控制台输出的日志的格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    # 指定文件中日志输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  level: debug

mybatis:
  configuration:
#    开启驼峰命名规则
    map-underscore-to-camel-case: true
# 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml

# 配置文件项加密密码，实际应用应放在代码中
jasypt:
  encryptor:
    password: sbo


